# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

neo_version=20.6.119
neo_version_range=[20.6,)
loader_version_range=[2,)
minecraft_version=1.20.6
minecraft_version_range=[1.20.6,1.21)

mod_id=warp_pipes
mod_name=WenXin's Warp Pipes
mod_version=2.2.4-neoforge
mod_group_id=com.wenxin2.warp_pipes
mod_license=GNU GPLv3
mod_authors=WenXin2
mod_description=This mod adds a new form of transportation from the Mario universe, the Warp Pipe!
mixin_location=warp_pipes.mixins.json

architectury_api_version=419699:5383746
cloth_config_version=348521:5287791
fusion_version=854949:5129341
jei_version=238222:5306217
moonlight_version=499980:5092530
rei_version=310111:5301358
spark_version=361579:5302031
structure_gel_version=378802:5391404

# connectedness_version=853916:4506203
# ctm_version=267602:4393695
# reforgium_version=853424:4505759
# supplementaries_version=412082:5340612