# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}"
# The license for you mod.
license="${mod_license}"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/WenXin20/WarpPipes/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
# The modid of the mod
modId="warp_pipes"
# The version number of the mod
version="${minecraft_version}-${mod_jar_version}"
# A display name for the mod
displayName="Warp Pipes"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/WenXin20/Warp-Pipes" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="warp_pipes_banner.png"
# A text field displayed in the mod UI
credits="Made by WenXin2"
# A text field displayed in the mod UI
authors="WenXin2"

# The description text for the mod (multi line!) (#mandatory)
description='''
  Warp Pipes!! A new method of transportation!
  '''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.warp_pipes]] #optional
# the modid of the dependency
modId="forge"
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true
# The version range of the dependency
versionRange="${forge_version_range}"
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"

[[dependencies.warp_pipes]]
modId="minecraft"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
